using FedericoNembrini.Maui.CustomDatePicker.Handlers;

namespace FedericoNembrini.Maui.CustomDatePicker
{
	public static class AppBuilderExtensions
	{
		/// <summary>
		/// Initializes Nullable Date Picker
		/// </summary>
		/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/>.</param>
		/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="NullableDatePicker"/>.</returns>
		public static MauiAppBuilder UseCustomDatePicker(this MauiAppBuilder builder)
		{
			builder.ConfigureMauiHandlers(h => h.AddHandler<NullableDatePicker, NullableDatePickerHandler>());

			return builder;
		}
	}
}
